// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaaetvayxshhzighhhhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhYWV0dmF5eHNoaHppZ2hoaGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTM2MjQsImV4cCI6MjA2MDM2OTYyNH0.LQHlYUDMiuXK0C6cFyMkbI5BI9LSR2_PuSLEAABz4vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);